title: КВИНЕРДЖИ - современное решение в агробизнесе
telephone: +38(097)8526935
email: ban1986x@gmail.com
name: kvinergy
description: ПАВЛОВНИЯ КВИНЕРДЖИ Современное решение в агробизнесе Компания “АРТАНД АГРО” Является официальным дистрибьютором Павловнии Квинерджи Наши
themecolor: '#202225'
imagehome: img/products/slider-2/forest-1.jpg
imagetitle: img/favicon/icon-leaves.png
url: 'http://pavlovnya.1gb.ua'
baseurl: '/'

plugins: [jekyll-paginate-v2]
category_dir: blog
pagination:
  enabled: true
  per_page: 5
  title: ':title - Страница :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2




exclude: ['node_modules', 'gulpfile.js', 'package.json', 'package-lock.json', 'js/common.js', 'npm-debug.log', '**/Thumbs.db', 'libs', 'scss', '**/*.DS_Store']
soc:
  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
  <li><a href="#"><i class="fa fa-instagram"></i></a></li>
  <li><a href="#"><i class="fa fa-rss"></i></a></li>

copyright: 'Копирование контента и размещение на других сайтах запрещено.'




# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
